# Generated by Django 4.2.9 on 2026-03-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_catalog_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='pdf_file',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
